Sprint1 g4
Iker-elorrieta/Reto3G4 pull request #1
Opened 2023-02-01 12:14 UTC by renessz

2023-02-02 09:38 UTC, Iker-elorrieta requested changes
No se puede abrir el proyecto cuando se descarga.

No se puede evaluar

2023-02-03 08:31 UTC, Iker-elorrieta requested changes
No llega al 100% de las pruebas
![image](https://user-images.githubusercontent.com/71759245/216549565-9482808a-c2cb-4be6-a226-db5c3c034d35.png)

Los objetos no están relacionados entre si, sobran String y hay que utilizar objetos, array etc, esto no es BD.
![image](https://user-images.githubusercontent.com/71759245/216550507-48940ca5-d952-4452-b60e-21efd78f379a.png)

La clase hora no hay que utilizar, en JAVA ya está resuelta esa problematica.

2023-02-03 08:31 UTC, Iker-elorrieta commented on bls/src/modelo/Cines.java
> +	private int num_salas;
numero de salas? Tendrá que incluir las salas no?

2023-02-03 08:31 UTC, Iker-elorrieta commented on bls/src/modelo/Cliente.java
> +	private String contraseña;
ñ?

2023-02-03 08:31 UTC, Iker-elorrieta commented on bls/src/modelo/Entradas.java
> +	private String nombreCines;
Nombres? en otro objeto? No es correcto

2023-02-03 08:31 UTC, Iker-elorrieta commented on bls/src/modelo/Entradas.java
> +	private Hora hora;
No se puede utilizar la clase Hora, hay que buscar algo nativo de Java

2023-02-03 08:31 UTC, Iker-elorrieta commented on bls/src/modelo/Entradas.java
> +	private String nombrePelicula;
solo una pelicula?

2023-02-03 08:31 UTC, Iker-elorrieta commented on bls/src/modelo/Entradas.java
> +	private int duracion;
duración aqui?

2023-02-03 08:31 UTC, Iker-elorrieta commented on bls/src/modelo/Hora.java
> +
Esta clase no hay que utilizarla

2023-02-03 08:31 UTC, Iker-elorrieta commented on bls/src/modelo/Salas.java
> +	private int id_cine;
No tiene que estar este atributo aqui

2023-02-03 08:31 UTC, Iker-elorrieta commented on bls/src/modelo/Sesiones.java
> +	private Hora hora;
y que película se da en la sesión?

2023-02-03 08:31 UTC, Iker-elorrieta commented on bls/src/test/testModelo.java
> +
Todos los test en el mismo archivo??

2023-02-07 12:55 UTC, priguti commented on bls/src/modelo/Cines.java
> +	private int num_salas;
ok

2023-02-07 12:56 UTC, priguti commented on bls/src/modelo/Cliente.java
> +	private String contraseña;
ok

2023-02-07 13:19 UTC, Iker-elorrieta requested changes
algunas relaciones no están bien

2023-02-07 13:19 UTC, Iker-elorrieta commented on bls/src/modelo/Entradas.java
> +	private Cines []cines;
En la sesión ya tenemos el cine y la entrada sólo será de un cliente.

2023-02-07 13:19 UTC, Iker-elorrieta commented on bls/src/modelo/Salas.java
> +	private Peliculas [] id_pelicula;
Las películas aquí?

2023-02-08 09:33 UTC, Iker-elorrieta requested changes
![image](https://user-images.githubusercontent.com/71759245/217489521-5928c8fe-c7a1-4e5b-bb29-1aeb1eaf807d.png)
Sigue con errores en el código. No se puede entregar con errores.
Sigue habiendo problemas ( y graves) con la relaciones.
4 vez, y estamos a martes, en lo que tengáis dudas, preguntad!

2023-02-08 09:33 UTC, Iker-elorrieta commented on bls/src/modelo/Entradas.java
> +	private Peliculas []peliculas;
Las entradas no son de peliculas, tiene que existir una relación con las horas, los dias... etdc..

2023-02-08 09:33 UTC, Iker-elorrieta commented on bls/src/modelo/Salas.java
> +	private Peliculas [] arrayPeliculas;
En las salas no se dan películas, falta la relación de horas y días

2023-02-08 09:33 UTC, Iker-elorrieta commented on bls/src/modelo/Sesiones.java
> +	private Peliculas[] arrayPelicula;
Cada sesión se da una película no varias

2023-02-08 09:33 UTC, Iker-elorrieta commented on bls/src/modelo/Sesiones.java
> +	private Date fecha;
Si utilizamos fecha y hora de tipo Date es mejor solo utilizar un atributo

2023-02-08 09:33 UTC, Iker-elorrieta commented on bls/src/modelo/Cines.java
> +	private Salas[] id_sala;
No se puede llamar id_sala, igual salas???

2023-02-08 09:33 UTC, Iker-elorrieta commented on bls/src/modelo/Cliente.java
> +	public String getContraseña() {
Método con ñ???

2023-02-08 09:33 UTC, Iker-elorrieta commented on bls/src/modelo/Salas.java
> +public class Salas {
Lo llamaría sala

2023-02-08 09:33 UTC, Iker-elorrieta commented on bls/src/modelo/Peliculas.java
> +	private int id_pelicula;
Lo llamaría pelicula

2023-02-08 09:33 UTC, Iker-elorrieta commented on bls/src/modelo/Sesiones.java
> +public class Sesiones {
Lo llamaría sesion

2023-02-08 09:33 UTC, Iker-elorrieta commented on bls/src/modelo/Entradas.java
> +public class Entradas {
Lo llamaría entrada

2023-02-08 09:33 UTC, Iker-elorrieta commented on bls/src/modelo/Cines.java
> +public class Cines {
Lo llamaría cine

2023-02-08 11:38 UTC, Iker-elorrieta requested changes
Faltan algunos detalles como el precio total de la entrada, y sobra alguno

2023-02-08 11:38 UTC, Iker-elorrieta commented on bls/src/modelo/Entrada.java
> +
falta el precio total de la entrada, incluyendo descuentos si aplica.

2023-02-08 11:38 UTC, Iker-elorrieta commented on bls/src/modelo/Cliente.java
> +	private int id_cliente;
Elegid un identificar de los dos.

2023-02-08 11:38 UTC, Iker-elorrieta commented on bls/src/modelo/Sala.java
> +	private int num_salas;
no es necesario conocer el número de salas dentro de cada sala

2023-02-08 11:38 UTC, Iker-elorrieta commented on bls/src/modelo/Sesion.java
> +	private Date hora;
Si utilizamos un tipo de dato que incluye fecha y hora, no es necesario utilizar dos campos

2023-02-08 11:53 UTC, Iker-elorrieta approved these changes
Todo ok, vamos!

2023-02-08 11:54 UTC, merged